/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-07-24 06:27:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.toolbar;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class toolbar_005fdark_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1690179985242L));
    _jspx_dependants.put("jar:file:/D:/hellow/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HelloWorld/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("<meta name=\"author\" content=\"\" />\n");
      out.write("<title>Hello Teams</title>\n");
      out.write("\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css\"\n");
      out.write("	rel=\"stylesheet\" />\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/styles.css\"\n");
      out.write("	rel=\"stylesheet\" />\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v6.3.0/js/all.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\"sb-nav-fixed\">\n");
      out.write("	<nav class=\"sb-topnav navbar navbar-expand navbar-dark bg-dark\">\n");
      out.write("		<!-- Navbar Brand-->\n");
      out.write("		<a class=\"navbar-brand ps-3\" href=\"");
      out.print(request.getContextPath());
      out.write("/ConnectMain.do\">Hello\n");
      out.write("			Teams</a>\n");
      out.write("		<!-- Sidebar Toggle-->\n");
      out.write("		<button class=\"btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0\"\n");
      out.write("			id=\"sidebarToggle\" href=\"#!\">\n");
      out.write("			<i class=\"fas fa-bars\"></i>\n");
      out.write("		</button>\n");
      out.write("		<button type=\"menu\"\n");
      out.write("			style=\"background-color: transparent; color: white; border: 0; outline: 0; margin: auto; font: bolder; font-size: x-large;\"\n");
      out.write("			onclick=\"#\">Project Name</button>\n");
      out.write("		<!-- Navbar-->\n");
      out.write("		<ul class=\"navbar-nav ms-auto ms-md-0 me-3 me-lg-4\">\n");
      out.write("			<li class=\"nav-item dropdown\"><a\n");
      out.write("				class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\"\n");
      out.write("				role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\"><i\n");
      out.write("					class=\"fas fa-user fa-fw\"></i></a>\n");
      out.write("				<ul class=\"dropdown-menu dropdown-menu-end\"\n");
      out.write("					aria-labelledby=\"navbarDropdown\">\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"#!\">Settings</a></li>\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"#!\">Activity Log</a></li>\n");
      out.write("					<li><hr class=\"dropdown-divider\" /></li>\n");
      out.write("					<li><a class=\"dropdown-item\" href=\"#!\">Logout</a></li>\n");
      out.write("				</ul></li>\n");
      out.write("		</ul>\n");
      out.write("	</nav>\n");
      out.write("	<div id=\"layoutSidenav\">\n");
      out.write("		<div id=\"layoutSidenav_nav\">\n");
      out.write("			<nav class=\"sb-sidenav accordion sb-sidenav-dark\"\n");
      out.write("				id=\"sidenavAccordion\">\n");
      out.write("				<div class=\"sb-sidenav-menu\">\n");
      out.write("					<div class=\"nav\">\n");
      out.write("						<div class=\"sb-sidenav-menu-heading\">홈</div>\n");
      out.write("						<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/ConnectMain.do\">\n");
      out.write("							메인페이지\n");
      out.write("						</a>\n");
      out.write("						<div class=\"sb-sidenav-menu-heading\">업무</div>\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\n");
      out.write("							data-bs-target=\"#collapseLayouts\" aria-expanded=\"false\"\n");
      out.write("							aria-controls=\"collapseLayouts\">\n");
      out.write("							<div class=\"sb-nav-link-icon\">\n");
      out.write("								<i class=\"fas fa-columns\"></i>\n");
      out.write("							</div> 업무 관련\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\n");
      out.write("							</div>\n");
      out.write("						</a>\n");
      out.write("						<div class=\"collapse\" id=\"collapseLayouts\"\n");
      out.write("							aria-labelledby=\"headingOne\" data-bs-parent=\"#sidenavAccordion\">\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav\">\n");
      out.write("								<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/SectionView.do\">프로젝트 섹션</a> <a\n");
      out.write("									class=\"nav-link\" href=\"layout-sidenav-light.jsp\">내 작업</a>\n");
      out.write("							</nav>\n");
      out.write("						</div>\n");
      out.write("						<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\n");
      out.write("							data-bs-target=\"#collapsePages\" aria-expanded=\"false\"\n");
      out.write("							aria-controls=\"collapsePages\">\n");
      out.write("							<div class=\"sb-nav-link-icon\">\n");
      out.write("								<i class=\"fas fa-book-open\"></i>\n");
      out.write("							</div> 커뮤니티\n");
      out.write("							<div class=\"sb-sidenav-collapse-arrow\">\n");
      out.write("								<i class=\"fas fa-angle-down\"></i>\n");
      out.write("							</div>\n");
      out.write("						</a>\n");
      out.write("						<div class=\"collapse\" id=\"collapsePages\"\n");
      out.write("							aria-labelledby=\"headingTwo\" data-bs-parent=\"#sidenavAccordion\">\n");
      out.write("							<nav class=\"sb-sidenav-menu-nested nav accordion\"\n");
      out.write("								id=\"sidenavAccordionPages\">\n");
      out.write("								<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\n");
      out.write("									data-bs-target=\"#pagesCollapseAuth\" aria-expanded=\"false\"\n");
      out.write("									aria-controls=\"pagesCollapseAuth\">게시판\n");
      out.write("									<div class=\"sb-sidenav-collapse-arrow\">\n");
      out.write("										<i class=\"fas fa-angle-down\"></i>\n");
      out.write("									</div>\n");
      out.write("								</a>\n");
      out.write("								<div class=\"collapse\" id=\"pagesCollapseAuth\"\n");
      out.write("									aria-labelledby=\"headingOne\"\n");
      out.write("									data-bs-parent=\"#sidenavAccordionPages\">\n");
      out.write("									<nav class=\"sb-sidenav-menu-nested nav\">\n");
      out.write("										<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/board/notice.do\">공지\n");
      out.write("											게시판</a> <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/board/list.do\">자유\n");
      out.write("											게시판</a> <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/board/write.do\">게시물\n");
      out.write("											작성</a>\n");
      out.write("									</nav>\n");
      out.write("								</div>\n");
      out.write("								<a class=\"nav-link collapsed\" href=\"#\" data-bs-toggle=\"collapse\"\n");
      out.write("									data-bs-target=\"#pagesCollapseError\" aria-expanded=\"false\"\n");
      out.write("									aria-controls=\"pagesCollapseError\">쪽지\n");
      out.write("									<div class=\"sb-sidenav-collapse-arrow\">\n");
      out.write("										<i class=\"fas fa-angle-down\"></i>\n");
      out.write("									</div>\n");
      out.write("								</a>\n");
      out.write("								<div class=\"collapse\" id=\"pagesCollapseError\"\n");
      out.write("									aria-labelledby=\"headingOne\"\n");
      out.write("									data-bs-parent=\"#sidenavAccordionPages\">\n");
      out.write("									<nav class=\"sb-sidenav-menu-nested nav\">\n");
      out.write("										<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/pro/receiveList.do\">받은\n");
      out.write("											쪽지함</a> <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/pro/SendList.do\">보낸\n");
      out.write("											쪽지함</a> <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/pro/keepList.do\">쪽지\n");
      out.write("											보관함</a>\n");
      out.write("									</nav>\n");
      out.write("								</div>\n");
      out.write("							</nav>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"sb-sidenav-menu-heading\"></div>\n");
      out.write("						<a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/Mypage.do\">\n");
      out.write("							<div class=\"sb-nav-link-icon\">\n");
      out.write("								<i class=\"fas fa-chart-area\"></i>\n");
      out.write("							</div> 마이 페이지\n");
      out.write("						</a> <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/Manage.jsp\">\n");
      out.write("							<div class=\"sb-nav-link-icon\">\n");
      out.write("								<i class=\"fas fa-table\"></i>\n");
      out.write("							</div> 관리자 페이지\n");
      out.write("						</a>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"sb-sidenav-footer\">\n");
      out.write("					<div class=\"small\">Logged in as:</div>\n");
      out.write("					Hello Teams\n");
      out.write("				</div>\n");
      out.write("			</nav>\n");
      out.write("		</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
