/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-24 06:47:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Section;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SectionPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/Section/TodoPopUp.jsp", Long.valueOf(1682317150383L));
    _jspx_dependants.put("/Section/EditTodo.jsp", Long.valueOf(1682317150383L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682317150397L));
    _jspx_dependants.put("jar:file:/D:/hellow/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HelloWorld/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("<title>프로젝트 섹션</title>\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css\"\n");
      out.write("	rel=\"stylesheet\" />\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" />\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/css/system.css\" rel=\"stylesheet\" />\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v6.3.0/js/all.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body class=\"sb-nav-fixed\">\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../toolbar/toolbar_dark.jsp", out, false);
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Todo Popup</title>\n");
      out.write("<link href=\"../css/system.css\" rel=\"stylesheet\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<div class=\"window_modal\">\n");
      out.write("		<div id=\"todoPopUp\" class=\"popup_modal\">\n");
      out.write("			<h2 style=\"text-align: center; margin-top:16px\">작업");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("</h2>\n");
      out.write("			<span id=\"close\" style=\"position: absolute; top: 10px; right: 20px; cursor:pointer;\">x</span>\n");
      out.write("			<form action=\"");
      out.print(request.getContextPath());
      out.write("/SectionTodo/addTodo.do\" \" method=\"post\"\n");
      out.write("				id=\"SectionPopUp\" style=\"width: 100%; height: 100%;\">\n");
      out.write("				<table style=\"margin: auto;\" id=\"PopUptable\">\n");
      out.write("					<tr>\n");
      out.write("						<td>섹션 선택 :</td>\n");
      out.write("						<td colspan=\"3\" style=\"align-content: center; padding-left: 6px\">\n");
      out.write("							<select style=\"width: 50%;\" name=\"section_id_todo\">\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("						</select>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td>작업 내용 :</td>\n");
      out.write("						<td style=\"padding-left: 6px\"><input type=\"text\"\n");
      out.write("							name=\"work_content\" id=\"\" placeholder=\"내용을 입력해주세요\"></td>\n");
      out.write("						</td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td>담당 선택 :</td>\n");
      out.write("						<td colspan=\"3\" style=\"padding-left: 6px\"><select\n");
      out.write("							style=\"width: 50%\" name=\"PIC\">\n");
      out.write("								");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("						</select>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td>상태</td>\n");
      out.write("						<td style=\"padding-left: 6px\"><select style=\"width: 50%\"\n");
      out.write("							name=\"work_status\">\n");
      out.write("								<option value=\"READY\">대기</option>\n");
      out.write("								<option value=\"START\">진행중</option>\n");
      out.write("								<option value=\"END\">완료</option>\n");
      out.write("						</select></td>\n");
      out.write("						<td>우선 순위</td>\n");
      out.write("						<td style=\"padding-left: 6px\"><select style=\"width: 50%\"\n");
      out.write("							name=\"work_rank\">\n");
      out.write("								<option value=\"HIGH\">높음</option>\n");
      out.write("								<option value=\"MIDDLE\">보통</option>\n");
      out.write("								<option value=\"LOW\">낮음</option>\n");
      out.write("						</select></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td>시작일</td>\n");
      out.write("						<td style=\"padding-left: 6px\"><input type=\"date\"\n");
      out.write("							name=\"work_start\"></td>\n");
      out.write("						<td>종료일</td>\n");
      out.write("						<td style=\"padding-left: 6px\"><input type=\"date\"\n");
      out.write("							name=\"work_end\"></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td colspan=\"2\"><input type=\"submit\" value=\"추가\"\n");
      out.write("							style=\"margin: auto;\"></td>\n");
      out.write("						<td colspan=\"2\"><input type=\"button\" onclick=\"\" value=\"취소\"></td>\n");
      out.write("					</tr>\n");
      out.write("\n");
      out.write("				</table>\n");
      out.write("			</form>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<script>\n");
      out.write("	window.addEventListener('click', (event) => {\n");
      out.write("			var modal = document.querySelector('.window_modal');\n");
      out.write("	    	if (event.target == modal) {\n");
      out.write("	    	toggleDisplay('none')\n");
      out.write("	    	}\n");
      out.write("		});\n");
      out.write("		function closeModal() {\n");
      out.write("			var modal = document.getElementById('todoPopUp');\n");
      out.write("			modal.classList.remove('showTodo');\n");
      out.write("			modal.classList.add('none');\n");
      out.write("		}\n");
      out.write("		function show() {\n");
      out.write("			document.querySelector(\".background_modal\").className = \"background_modal show_modal\";\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		const modal = document.querySelector('.window_modal');\n");
      out.write("		\n");
      out.write("		function toggleDisplay(display) {\n");
      out.write("			modal.style.display = display;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		document.querySelector(\"#close\").addEventListener('click', () => toggleDisplay('none'))\n");
      out.write("	</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	<div id=\"layoutSidenav_content\">\n");
      out.write("		<main>\n");
      out.write("			<div class=\"container-fluid px-4\">\n");
      out.write("				<h1 class=\"mt-5\">프로젝트 섹션</h1>\n");
      out.write("				<ol class=\"breadcrumb mb-4\">\n");
      out.write("					<li class=\"breadcrumb-item active\"></li>\n");
      out.write("				</ol>\n");
      out.write("				<button id=\"show_modal\"\n");
      out.write("					style=\"border: 1px solid gray; margin-bottom: 5px; border-radius: 8px;\">+\n");
      out.write("					작업 추가</button>\n");
      out.write("				<div class=\"card mb-5\">\n");
      out.write("					<div class=\"card-header\">\n");
      out.write("						<i class=\"fas fa-table me-1\"></i>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"card-body\">\n");
      out.write("						<div>\n");
      out.write("							<ul class=\"sect_id_check\" style=\"line-height: 2em;\">\n");
      out.write("					");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				</ul>\n");
      out.write("						</div>\n");
      out.write("					<div id =\"section_div\" class=\"none\">\n");
      out.write("						<input type=\"text\" placeholder=\"섹션 명을 입력해주세요.\" id=\"create_section\"/><button id=\"btn_cre_sect\">생성</button>\n");
      out.write("					</div>\n");
      out.write("						<button id=\"show_sect_create_div\">+ 섹션 추가</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("#chatId {\n");
      out.write("   width: 158px;\n");
      out.write("   height: 24px;\n");
      out.write("   border: 1px solid #AAAAAA;\n");
      out.write("   background-color: #EEEEEE;\n");
      out.write("   }\n");
      out.write("#sidePop{\n");
      out.write("   min-width: 425px;\n");
      out.write("   margin-left: 77%;\n");
      out.write("   }\n");
      out.write(".popUpForm{\n");
      out.write("max-width: 425px;\n");
      out.write("    width: 100%;\n");
      out.write("    display: flex;\n");
      out.write("    height: 40%;\n");
      out.write("    flex-direction: column;\n");
      out.write("    justify-content: space-between;\n");
      out.write("    align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write(".width_max_per{\n");
      out.write("width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("   <div id=\"sidePop\">\n");
      out.write("      <form action=\"");
      out.print(request.getContextPath());
      out.write("/SectionTodo/editTodo.do\" method=\"post\" class=\"popUpForm\">\n");
      out.write("         <input type=\"text\" name=\"edit_todo\" id=\"edit_todo\" placeholder=\"할 일 입력\" style=\"width: 100%;\">\n");
      out.write("         <input type=\"text\" name=\"edit_todo_id\" id=\"edit_todo_id\" style=\"display:none\">\n");
      out.write("         <table style=\"height: 70%; width: 100%;\">\n");
      out.write("            <tr>\n");
      out.write("               <th>담당자 : </th>\n");
      out.write("               <td><select name=\"edit_PIC_name\" id=\"todo_name\">\n");
      out.write("                     ");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("               </select></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("               <th>마감일</th>\n");
      out.write("               <td><input type=\"date\" name=\"edit_end_date\" id=\"edit_end_date\" value=\"2023-01-01\"></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("               <th>섹션 명 : </th>\n");
      out.write("               <td>\n");
      out.write("                  <select name=\"edit_Section\" id=\"edit_sectName\">\n");
      out.write("                     ");
      if (_jspx_meth_c_005fforEach_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("               </select></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("               <th>상태</th>\n");
      out.write("               <td><input type=\"text\" name=\"edit_status\" id=\"edit_status\" value=\"상태\"></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("               <th>설명</th>\n");
      out.write("               <td><input type=\"text\" name=\"edit_info\" id=\"edit_info\" value=\"설 명\"></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("               <td colspan=\"2\" style=\"text-align: end;\"><input\n");
      out.write("                  type=\"submit\" value=\"변경\"></td>\n");
      out.write("            </tr>\n");
      out.write("         </table>\n");
      out.write("         <div style=\"width: 100%;\">\n");
      out.write("            \n");
      out.write("            <input type=\"text\" id=\"chatMessage\" onkeyup=\"enterKey();\" style=\"width:88%;\">\n");
      out.write("            <button id=\"edit_SendBtn\" onclick=\"\">전송</button>\n");
      out.write("         </div>\n");
      out.write("      </form>\n");
      out.write("\n");
      out.write("   </div>\n");
      out.write("   <script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"\n");
      out.write("      integrity=\"sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=\"\n");
      out.write("      crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>");
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</main>\n");
      out.write("		<footer class=\"py-4 bg-light mt-auto\">\n");
      out.write("			<div class=\"container-fluid px-4\">\n");
      out.write("				\n");
      out.write("			</div>\n");
      out.write("		</footer>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/scripts.js\"></script>\n");
      out.write("\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/js/datatables-simple-demo.js\"></script>\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"\n");
      out.write("		integrity=\"sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("	function openModal() {\n");
      out.write("	    var modal = document.getElementById('todoPopUp');\n");
      out.write("	    modal.classList.remove('none');\n");
      out.write("	    modal.classList.add('showTodo');\n");
      out.write("	}\n");
      out.write("	  \n");
      out.write("	  \n");
      out.write("	const modalBtn = document.querySelector('#show_modal');\n");
      out.write("	  \n");
      out.write("	modalBtn.addEventListener('click', () => toggleDisplay('block'));\n");
      out.write("\n");
      out.write("	if($(\"#section_div\").attr('class')==\"showTodo\"){\n");
      out.write("		$('div').click(function(){\n");
      out.write("			$(\"#section_div\").addClass(\"none\");\n");
      out.write("			$(\"#section_div\").removeClass(\"showTodo\");		\n");
      out.write("		})\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	$(\"#show_sect_create_div\").on('click',(e)=>{\n");
      out.write("		if($(\"#section_div\").attr('class')==\"showTodo\"){\n");
      out.write("			$(\"#section_div\").addClass(\"none\");\n");
      out.write("			$(\"#section_div\").removeClass(\"showTodo\");\n");
      out.write("		}else{		\n");
      out.write("			$(\"#section_div\").addClass(\"showTodo\");\n");
      out.write("			$(\"#section_div\").removeClass(\"none\");\n");
      out.write("		}\n");
      out.write("	})\n");
      out.write("		\n");
      out.write("	$(\"#btn_cre_sect\").on('click',(e)=>{\n");
      out.write("		$.ajax({\n");
      out.write("			url : \"./SectionTodo/addSection.do\",  // 요청 URL\n");
      out.write("			type : \"post\",                  // HTTP 메서드\n");
      out.write("			data : {                       // 매개변수로 전달할 데이터\n");
      out.write("				create_sec_Name : $(\"#create_section\").val()\n");
      out.write("			},\n");
      out.write("			dataType : \"text\",      // 응답 데이터 형식\n");
      out.write("			success : function(){\n");
      out.write("				alert(\"생성되었습니다.\")\n");
      out.write("				location.reload();\n");
      out.write("			},\n");
      out.write("			error : function(){\n");
      out.write("				alert(\"tlqkf\");\n");
      out.write("			}\n");
      out.write("			})\n");
      out.write("	})\n");
      out.write("	$(\".btn_del_sect\").on('click',(e)=>{\n");
      out.write("		console.log($(e.target).val());\n");
      out.write("		let count = 0;\n");
      out.write("		let leng = $(e.target).parent().next().children().find('input')\n");
      out.write("		leng.each(function(){\n");
      out.write("			if($(this).prop(\"checked\")){\n");
      out.write("				console.log($(this).prop(\"checked\"));	\n");
      out.write("				count++;\n");
      out.write("			}\n");
      out.write("		})\n");
      out.write("			if(leng.length==count || count==0){\n");
      out.write("				console.log(\"아작스 실행\")\n");
      out.write("				if(confirm('정말 삭제하시겠습니까?')){\n");
      out.write("					$.ajax({\n");
      out.write("						url : \"../SectionTodo/SecDel.do\",  // 요청 URL\n");
      out.write("						type : \"post\",                  // HTTP 메서드\n");
      out.write("						data : {                       // 매개변수로 전달할 데이터\n");
      out.write("							section_id : $(e.target).val()\n");
      out.write("						},\n");
      out.write("						dataType : \"text\",      // 응답 데이터 형식\n");
      out.write("						success : function(){\n");
      out.write("							alert(\"삭제되었습니다.\")\n");
      out.write("							location.reload();\n");
      out.write("						},\n");
      out.write("						error : function(){\n");
      out.write("							alert(\"tlqkf\");\n");
      out.write("						}\n");
      out.write("					})\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("			else{\n");
      out.write("				alert(\"삭제 하지마\");\n");
      out.write("			}\n");
      out.write("\n");
      out.write("\n");
      out.write("		\n");
      out.write("	})\n");
      out.write("		//if($(e.target).parent().next().children().find('input[checked=\"true\"]').length==leng){\n");
      out.write("		//}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	$(\".td_check\").on('click',(e)=>{\n");
      out.write("		//console.log($(e.target).prev().nextUntil('span[class=\"td_todo_status\"]'))\n");
      out.write("		console.log($(e.target).val());\n");
      out.write("		if($(e.target).is(':checked')){\n");
      out.write("			$.ajax({\n");
      out.write("				url : \"");
      out.print(request.getContextPath());
      out.write("/SectionTodo/status.do\",  // 요청 URL\n");
      out.write("				type : \"post\",                  // HTTP 메서드\n");
      out.write("				data : {                       // 매개변수로 전달할 데이터\n");
      out.write("					todo_id : $(e.target).val()\n");
      out.write("				},\n");
      out.write("				dataType : \"text\",      // 응답 데이터 형식\n");
      out.write("				success : function(){\n");
      out.write("					$(e.target).nextUntil('span[class=\"td_todo_status\"]').next().css({\"text-decoration\": \"line-through\", \"color\": \"gray\"});\n");
      out.write("					$(e.target).next().next().next().next().next().text(\"END\");\n");
      out.write("					$(e.target).next().next().next().next().next().next().next().next().next().next().next().next().addClass(\"none\");\n");
      out.write("					//location.reload();\n");
      out.write("				},\n");
      out.write("				error : function(){\n");
      out.write("					alert(\"tlqkf\");\n");
      out.write("				}\n");
      out.write("			})\n");
      out.write("		}\n");
      out.write("		else{\n");
      out.write("			$(e.target).nextUntil('span[class=\"td_todo_status\"]').next().css({\"text-decoration\": \"\", \"color\": \"\"});\n");
      out.write("			$(e.target).next().next().next().next().next().text(\"START\");\n");
      out.write("			\n");
      out.write("			$(e.target).next().next().next().next().next().next().next().next().next().next().next().next().removeClass(\"none\");\n");
      out.write("			$(e.target).next().next().next().next().next().next().next().next().next().next().next().next().addClass(\"inline_span\");\n");
      out.write("		}\n");
      out.write("	});\n");
      out.write("		\n");
      out.write("	  \n");
      out.write("	  \n");
      out.write("	$(\".btn_show_hide\").on('click',(e)=>{\n");
      out.write("		let a = $(e.target).parent().next();\n");
      out.write("		if(a.is(\"ul\")){\n");
      out.write("			a.toggle();\n");
      out.write("		}\n");
      out.write("	})\n");
      out.write("		\n");
      out.write("	$(\".btn_del_todo\").on('click',(e)=>{\n");
      out.write("		if(confirm('정말 삭제하시겠습니까?')){\n");
      out.write("			$.ajax({\n");
      out.write("		 	    url : \"./SectionTodo/todoDelete.do\",  // 요청 URL\n");
      out.write("		 	    type : \"post\",                  // HTTP 메서드\n");
      out.write("		 	    data : {                       // 매개변수로 전달할 데이터\n");
      out.write("		 	        todo_id : $(e.target).val()\n");
      out.write("		 	        },\n");
      out.write("		 	    dataType : \"text\",      // 응답 데이터 형식\n");
      out.write("		 	    success : function(){\n");
      out.write("		 	    	location.reload();\n");
      out.write("		 	    },\n");
      out.write("		 	    		  // 요청 성공 시 호출할 메서드 설정\n");
      out.write("		 	    error : function(){\n");
      out.write("		 	    	alert(\"tlqkf\");\n");
      out.write("		 	    }         // 요청 실패 시 호출할 메서드 설정\n");
      out.write("			});\n");
      out.write("		}\n");
      out.write("	})\n");
      out.write("\n");
      out.write("\n");
      out.write("	$(\".edit_todo_btn\").on('click',(e)=>{\n");
      out.write("		var content = $(e.target).parent().parent().children()[1].textContent; //할일 내용\n");
      out.write("	    var name = $(e.target).parent().parent().children()[2].textContent; //담당자 이름\n");
      out.write("	    var todo_id = $(e.target).parent().parent().children()[7].textContent; //할일 id\n");
      out.write("	    var name_id = $(e.target).parent().parent().children()[8].textContent; //담당자 이름\n");
      out.write("	    var sect_id = $(e.target).parent().parent().children()[9].textContent; //\n");
      out.write("	    var sect_name = $(e.target).parent().parent().children()[10].textContent;\n");
      out.write("	    var end_date = $(e.target).parent().parent().children()[4].textContent;\n");
      out.write("	    var status = $(e.target).parent().parent().children()[5].textContent;\n");
      out.write("	    var info = $(e.target).parent().parent().children()[6].textContent;\n");
      out.write("		console.log(todo_id);\n");
      out.write("		//값 넘기기\n");
      out.write("		$(\"#edit_todo\").val(content);	//수정 창에 할일 값\n");
      out.write("	    $(\"#todo_name\").val(name_id).prop(\"selected\",true);		//작성자\n");
      out.write("	    $(\"#edit_todo_id\").val(todo_id);\n");
      out.write("	    $(\"#edit_end_date\").val(end_date); //마감일\n");
      out.write("	    $(\"#edit_sectName\").val(sect_id).prop(\"selected\",true); //섹션 명\n");
      out.write("	    $(\"#edit_status\").val(status);	//상태\n");
      out.write("	    $(\"#edit_info\").val(info);	//설명\n");
      out.write("	})\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Section/TodoPopUp.jsp(14,53) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(false);
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('추');
          out.write('가');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /Section/TodoPopUp.jsp(23,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/Section/TodoPopUp.jsp(23,8) '${sectionList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sectionList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Section/TodoPopUp.jsp(23,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      // /Section/TodoPopUp.jsp(23,8) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("stat");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("									<option name=\"section_id_todo\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.section_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.section_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /Section/TodoPopUp.jsp(38,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/Section/TodoPopUp.jsp(38,8) '${projectMem}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${projectMem}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Section/TodoPopUp.jsp(38,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("mem");
      // /Section/TodoPopUp.jsp(38,8) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("stat");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("									<option name=\"PIC\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem.pro_mem_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem.pro_member}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\n");
            out.write("								");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("						");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /Section/SectionPage.jsp(42,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sectionList.size()==0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("							<li>프로젝트 섹션이 나누어지지 않았습니다.</li>\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("							");
          if (_jspx_meth_c_005fforEach_005f2(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /Section/SectionPage.jsp(46,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/Section/SectionPage.jsp(46,7) '${sectionList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sectionList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Section/SectionPage.jsp(46,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("list");
      // /Section/SectionPage.jsp(46,7) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVarStatus("stat");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("								<li>\n");
            out.write("									<button class=\"btn_show_hide\" style=\"background: none;border: none;font-weight: bolder;\"\n");
            out.write("										type=\"button\" name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.section_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\n");
            out.write("										value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.section_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write(' ');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.section_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</button>\n");
            out.write("									\n");
            out.write("										<button>\n");
            out.write("											<i class=\"fas fa-ellipsis-h\"></i>\n");
            out.write("										</button>\n");
            out.write("									<button class=\"btn_keep_sect\">보관</button>\n");
            out.write("									<button class=\"btn_del_sect\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.section_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">삭제</button>\n");
            out.write("								</li>\n");
            out.write("								<ul style=\"display: none\">\n");
            out.write("									");
            if (_jspx_meth_c_005fforEach_005f3(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\n");
            out.write("								</ul>\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /Section/SectionPage.jsp(59,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/Section/SectionPage.jsp(59,9) '${todoList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${todoList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Section/SectionPage.jsp(59,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("tlist");
      // /Section/SectionPage.jsp(59,9) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVarStatus("stat");
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("										");
            if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fforEach_005f3, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f3))
              return true;
            out.write("\n");
            out.write("									");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f3, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f3);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("											");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f3))
            return true;
          out.write("\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f3)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /Section/SectionPage.jsp(61,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.section_id eq tlist.section_Id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("												<li>\n");
          out.write("													<input type=\"checkbox\" class=\"td_check\">\n");
          out.write("													<span class=\"td_todo_content\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tlist.todo_Content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("													<span class=\"td_todo_part\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tlist.part_Name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("													<span class=\"td_todo_date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tlist.todo_Start_Date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("													<span class=\"td_todo_date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tlist.todo_End_Date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("													<span class=\"td_todo_status\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tlist.todo_Status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("													<span style=\"display:none\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tlist.todo_info}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("													<span style=\"display:none\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tlist.todo_Id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("													<span style=\"display:none\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tlist.part_Id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("													<span style=\"display:none\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.section_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\n");
          out.write("													<span style=\"display:none\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.section_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>													\n");
          out.write("													<span>\n");
          out.write("														<button class=\"pop_edit_del\"type=\"button\">\n");
          out.write("															<i class=\"fas fa-ellipsis-h\"></i>\n");
          out.write("														</button>\n");
          out.write("													</span>\n");
          out.write("													<span><button class=\"edit_todo_btn\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tlist.part_Name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(',');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tlist.todo_Content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">수정</button></span>\n");
          out.write("													<span><button class=\"btn_del_todo\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tlist.todo_Id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">삭제</button></span>\n");
          out.write("													\n");
          out.write("												</li>\n");
          out.write("											");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f4_reused = false;
    try {
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent(null);
      // /Section/EditTodo.jsp(42,21) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/Section/EditTodo.jsp(42,21) '${projectMem}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${projectMem}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Section/EditTodo.jsp(42,21) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVar("mem");
      // /Section/EditTodo.jsp(42,21) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVarStatus("stat");
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                        <option name=\"edit_PIC\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem.pro_mem_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mem.pro_member}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\n");
            out.write("                     ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
      _jspx_th_c_005fforEach_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f5_reused = false;
    try {
      _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f5.setParent(null);
      // /Section/EditTodo.jsp(55,21) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setItems(new org.apache.jasper.el.JspValueExpression("/Section/EditTodo.jsp(55,21) '${sectionList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sectionList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /Section/EditTodo.jsp(55,21) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setVar("list");
      // /Section/EditTodo.jsp(55,21) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setVarStatus("stat");
      int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
        if (_jspx_eval_c_005fforEach_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                        <option name=\"edit_Section\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.section_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.section_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\n");
            out.write("                     ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f5);
      _jspx_th_c_005fforEach_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f5_reused);
    }
    return false;
  }
}
